package main

import (
	reddit_handler "reddit-newsletter/apis"

	"github.com/gin-gonic/gin"
)

func main() {
	accessToken := "eyJhbGciOiJSUzI1NiIsImtpZCI6IlNIQTI1NjpzS3dsMnlsV0VtMjVmcXhwTU40cWY4MXE2OWFFdWFyMnpLMUdhVGxjdWNZIiwidHlwIjoiSldUIn0.eyJzdWIiOiJ1c2VyIiwiZXhwIjoxNzExOTQ5NjA0LjM2MjgzNCwiaWF0IjoxNzExODYzMjA0LjM2MjgzNCwianRpIjoiY0RFalFkX1hqXzQyOG1Ja0xaT2ZXQUtxaWljVThnIiwiY2lkIjoicUk0bVgwQUctRGNaTFBEeWRZMHJtZyIsImxpZCI6InQyX2o0YnEwc3p4IiwiYWlkIjoidDJfajRicTBzengiLCJsY2EiOjE2NDMzOTc5MjcwMDAsInNjcCI6ImVKeUtWdEpTaWdVRUFBRF9fd056QVNjIiwiZmxvIjo5fQ.DhbwopzsUAycGiBDFxFbWVewUw5Z-qmca1oFC-IJhMq7uRaBzakHWvf0jEGKjR1_zJZXir5hj65asccu8yXALKK1YIGVO5r-3UPHnl6_ZxybRW4hKRU6flpc-GGITLxuICAlIe5DnFkhfQ2OVXGyzMrW_KK7SKSyQe5fPrlqmNhxt4PAPujBDKzvPekKTPxvN_bk1d1JRW-MVrYm6StP3q21rvmvYy_rK6QjdOeasQ4qYqUyb2oCSrmeLnhBO6l2Ck4tMkQTDDS4NxiU-MGyVv1vNA1Oqp_3MwUDKayppnTVys7APqy6BnJ8z8FzHhrUPEB_FM5TqmOjYCjS-6kL4A"
	rc := reddit_handler.NewRedditClient(accessToken)
	r := gin.Default()

	r.GET("/subreddits", rc.GetSubredditsHandler)
	r.GET("/hotpostsandcomments", rc.GetHotPostsAndCommentsHandler)

	r.Run(":8080")
}
