name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH client and rsync
        run: |
          sudo apt-get update -y
          sudo apt-get install -y openssh-client rsync
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_EC2_KEY }}" > ~/.ssh/ssh-key.pem
          chmod 400 ~/.ssh/ssh-key.pem
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          
      - name: Test connection to EC2
        run: |
          ssh -i ~/.ssh/ssh-key.pem ubuntu@${{ secrets.AWS_EC2_CONN_ID }} "echo 'Connection successful!'"
      - name: Upload Firebase Keys
        run: |
          # Decode the base64 string
          echo "${{ secrets.REDDIT_NEWSLETTER_FIREBASE_KEY }}" | base64 --decode > reddit-newsletter-firebase-key.json
          # Transfer the file to the EC2 instance
          scp -i ~/.ssh/ssh-key.pem reddit-newsletter-firebase-key.json ubuntu@${{ secrets.AWS_EC2_CONN_ID }}:reddit-newsletter/email-handler/reddit-newsletter-firebase-key.json
          scp -i ~/.ssh/ssh-key.pem reddit-newsletter-firebase-key.json ubuntu@${{ secrets.AWS_EC2_CONN_ID }}:reddit-newsletter/gpt-summarizer/reddit-newsletter-firebase-key.json
          scp -i ~/.ssh/ssh-key.pem reddit-newsletter-firebase-key.json ubuntu@${{ secrets.AWS_EC2_CONN_ID }}:reddit-newsletter/reddit-handler/reddit-newsletter-firebase-key.json
      - name: Deploy Docker Compose to EC2
        run: |
          ssh -T -i ~/.ssh/ssh-key.pem ubuntu@${{ secrets.AWS_EC2_CONN_ID }} '
            set -x;  # Enable debugging
            if [ -d reddit-newsletter ]; 
            then 
              cd reddit-newsletter &&
              git status &&
              git pull --rebase &&
              git status;
            else
              git clone https://github.com/aniqp/reddit-newsletter.git &&
              cd reddit-newsletter;
          '
        
